<a href="https://colab.research.google.com/github/PoPodada/Prog2kakushin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ホテル又はカラオケといった部屋の予約の場面を想定しています．

プログラムを実行した際に入室か退室かを聞かれ入室であれば，どの部屋が利用できるのかの候補を表示使いたい部屋を入力するとその部屋が埋まり表示されます．

退室を選んだ際は，どの部屋を使っていたかを聞かれその部屋が空室になります．

停止と入力するとプログラムを停止することが出来ます．

numpyを使ってプログラムを作成する

In [49]:
import numpy as np
#numpyをインポートしてください

In [50]:
room_row = np.array([[101,102,103,104],[201,202,203,204],[301,302,303,304],[401,402,403,0]])
room_max= np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
format_room=np.array([[101,102,103,104],[201,202,203,204],[301,302,303,304],[401,402,403,404]])
print(room_row)
print(room_max)
print(format_room)
#プログラムを実行する際に必要なデータです

[[101 102 103 104]
 [201 202 203 204]
 [301 302 303 304]
 [401 402 403   0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[101 102 103 104]
 [201 202 203 204]
 [301 302 303 304]
 [401 402 403 404]]


In [51]:

while True:
  which_question=input("入室と退室のどちらですか：")#入室か退室かのどちらかを聞かれるので入室又は退室を入力（停止と入力するとプログラムが止められます）
  
  if which_question=="入室":
    print("現在の部屋の候補として")
    print(room_row[room_row != room_max])
    question=int(input("好きな部屋を入力してください:"))#候補として表示された部屋を入力
    room_row=np.where(question==room_row,0, room_row)
    print(room_row)
    print(f"{question}の部屋が埋まりました")
  elif which_question=="退室":
    leaving_room=int(input("どの部屋を使っていましたか？："))#埋まっている部屋を入力
    room_row=np.where(leaving_room==format_room,leaving_room,room_row)
    print(room_row)
    print("ご利用ありがとうございました")
  elif which_question=="停止":
    print("プログラムを停止しました")
    break
  

入室と退室のどちらですか：入室
現在の部屋の候補として
[101 102 103 104 201 202 203 204 301 302 303 304 401 402 403]
好きな部屋を入力してください:101
[[  0 102 103 104]
 [201 202 203 204]
 [301 302 303 304]
 [401 402 403   0]]
101の部屋が埋まりました
入室と退室のどちらですか：入室
現在の部屋の候補として
[102 103 104 201 202 203 204 301 302 303 304 401 402 403]
好きな部屋を入力してください:203
[[  0 102 103 104]
 [201 202   0 204]
 [301 302 303 304]
 [401 402 403   0]]
203の部屋が埋まりました
入室と退室のどちらですか：退室
どの部屋を使っていましたか？：203
[[  0 102 103 104]
 [201 202 203 204]
 [301 302 303 304]
 [401 402 403   0]]
ご利用ありがとうございました
入室と退室のどちらですか：停止
プログラムを停止しました
